// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNdwvVIDBJxq_I4nkaPH4kysJv0Ld_Lnw',
    appId: '1:563969698096:web:8e2c881ceb6260940580f5',
    messagingSenderId: '563969698096',
    projectId: 'ecotask-5edaa',
    authDomain: 'ecotask-5edaa.firebaseapp.com',
    storageBucket: 'ecotask-5edaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIkIIUL9fyMk8tlgE7GZItQZX4r3WIREs',
    appId: '1:563969698096:android:3fe6eeab1a7e4c9d0580f5',
    messagingSenderId: '563969698096',
    projectId: 'ecotask-5edaa',
    storageBucket: 'ecotask-5edaa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNdwvVIDBJxq_I4nkaPH4kysJv0Ld_Lnw',
    appId: '1:563969698096:web:29c34aa43407c0310580f5',
    messagingSenderId: '563969698096',
    projectId: 'ecotask-5edaa',
    authDomain: 'ecotask-5edaa.firebaseapp.com',
    storageBucket: 'ecotask-5edaa.firebasestorage.app',
  );
}
